baseurl: http://yhzhtk.info
#本地调试用/blog，上传时改成域名
#baseurl: /blog
url: http://yhzhtk.info

title: Yhzhtk Pages（技术博客）
name: Yhzhtk's Blog
author: Daihui Gu
email: yhzhtk@gmail.com

# 首页每页显示博客数
paginate: 5

